### ISSUE TITLE
invalid includes/type names of fixed-width integers

### ISSUE THREAD

**Issue by Xeverous** [juliobg/asio_http#1]
Various headers include `<cstdint>` which is guuarantees only `std::uint64_t` and other `std::*_t` types. To use `uint64_t` without risk of compilation errors, one must inlude (deprecated) header `<stdint.h>`.

Since the library includes new (C++11) `<cstdint>`, it should use `std::*_t` type names (or make aliases for them in it's namespace).

**Comment by juliobg** [comment]
Thanks for pointing it out. I fixed in latest commit, e5d884b. I am closing the issue, as in case I missed to fix any of them, it should be considered an isolated occurrence, and not a general issue like this one.
