### ISSUE TITLE
Differences from Boost Beast?

### ISSUE THREAD

**Issue by Xeverous** [juliobg/asio_http#2]
This library offers similar functionality to Boost Beast. And both depends on ASIO. I think it would be worthwhile to list differences in features.

**Comment by juliobg** [comment]
I don't know Boost Beast very well, I started working on this library even before it was popular. Considering some examples I have seen on using Beast, I can say it seems intended as building blocks for lower level HTTP operations. I.e., it seems you need to call some function to write te request, them another one to await the response, etc.

This library is thought to offer an HTTP client that is able to manage several simultaneous requests, in a similar fashion to Python Tornado or .NET HttpClient class. I.e., a HTTP request can be performed with few lines of code.

Even if there is some duplication, I would say this library may be refactored to use Boost Beast for lower level HTTP operations, or HTTP parsing. Right now it is using Joyent HTTP parser.

Hope this answer makes it clear. I would add to readme.md later.

**Comment by juliobg** [comment]
I close this issue, as I added a couple of comments to readme.md indicating that both libraries, to some extent, sever different purposes (high level HTTP client and low level HTTP library).
